services:
  smartheads-app:
    build:
      context: .docker/
    volumes:
      - ".:/var/www/html"
    networks:
      - smartheads-task

  smartheads-nginx:
    image: nginx:stable-alpine
    depends_on:
      - smartheads-app
    networks:
      - smartheads-task
    volumes:
      - ".docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - ".:/var/www/html"

  smartheads-db:
    image: postgres:17.2
    restart: always
    environment:
      POSTGRES_USER: smartheads
      POSTGRES_PASSWORD: test321
      POSTGRES_DB: smartheads_db
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - smartheads-task

  smartheads-mailer:
    image: schickling/mailcatcher
    networks:
      - smartheads-task

networks:
  smartheads-task:
    external: true

volumes:
  dbdata: ~