parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Smartheads\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
